repos:
  - repo: local
    hooks:
      - id: check
        name: check
        entry: bun run check
        language: system
        pass_filenames: false
      - id: lint
        name: lint
        entry: bun run lint
        language: system
        pass_filenames: false
